---
deployment:
  tasks:
    - export DEPLOYPATH=/home/beelkstc/public_html/
    - /bin/cp -R * $DEPLOYPATH
    - /bin/cp -R .env.production $DEPLOYPATH/.env
    - cd $DEPLOYPATH
    # Configure composer with proper settings for PHP 8.0 hosting
    - composer config process-timeout 600
    - composer config --no-plugins allow-plugins.php-http/discovery true
    - composer config --no-plugins allow-plugins.pixelfear/composer-dist-plugin true
    - composer config --no-plugins allow-plugins.pestphp/pest-plugin true
    # Install dependencies ignoring platform requirements for PHP 8.0 compatibility
    - composer install --no-dev --optimize-autoloader --no-interaction --prefer-dist --ignore-platform-reqs --no-progress
    # Remove platform check to prevent PHP version errors
    - rm -f vendor/composer/platform_check.php
    - php artisan config:cache
    - php artisan route:cache
    - php artisan view:cache
    - php artisan statamic:stache:clear
    - php artisan statamic:stache:warm
    - chmod -R 755 storage bootstrap/cache
