name: thilacoloma-statamic
type: laravel
docroot: public
php_version: "8.3"
webserver_type: nginx-fpm
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
database:
  type: mysql
  version: "8.0"
use_dns_when_possible: true
composer_version: "2"

# Laravel/Statamic specific configuration
web_environment:
  - APP_ENV=local
  - APP_DEBUG=true
  - APP_URL=https://thilacoloma-statamic.ddev.site

# Enable router for Laravel
router_https_port: "443"
router_http_port: "80"
